name = "digital-sun-saas-factory"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-03-31"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
NEXT_PUBLIC_SITE_URL = "https://tu-dominio-en-cloudflare.pages.dev"

[triggers]
crons = ["*/30 * * * *"]
